name: Setup Environment
description: Set up the environment for vcpkg and CMake
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: /opt/vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('tools/installer/install_ubuntu.sh') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Install dependencies
      run: |
#        if [ ! -d /opt/vcpkg ]; then
          chmod +x tools/installer/install_ubuntu.sh
          tools/installer/install_ubuntu.sh
#        fi
      shell: bash

    - name: Clean vcpkg cache
      if: success()
      run: |
        rm -rf /opt/vcpkg/buildtrees /opt/vcpkg/downloads /opt/vcpkg/packages
      shell: bash

    - name: Create build directory
      run: mkdir -p build
      shell: bash

    - name: Configure with CMake
      run: |
        cd build
        cmake .. \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: bash

    - name: Build with CMake
      run: |
        cd build
        cmake --build .
      shell: bash
