version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  gateway:
    image: ghcr.io/mindspectre/gateway:1.0.0
    container_name: gateway-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network

  librarian_service:
    image: ghcr.io/mindspectre/librarian_service:1.0.0
    container_name: librarian-service-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app_network

  search_service:
    image: ghcr.io/mindspectre/search_service:1.0.0
    container_name: search-service-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - app_network

  frontend:
    image: ghcr.io/mindspectre/frontend:1.0.0
    container_name: frontend-container
    depends_on:
      - gateway
    ports:
      - "80:3001"
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
