name: C++ CI with CTest and vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Integration Tests
        run: |
          cd build
          ctest --output-on-failure -L integration

  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure -L unit
