name: C++ CI with CTest and vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: /opt/vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('tools/installer/install.sh') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ ! -d /opt/vcpkg ]; then
            chmod +x tools/installer/install.sh
            tools/installer/install.sh
          fi

      - name: Clean vcpkg cache
        if: success()
        run: |
          rm -rf /opt/vcpkg/buildtrees /opt/vcpkg/downloads /opt/vcpkg/packages

  configure:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: |
          cd build
          cmake .. \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake

  build:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with CMake
        run: |
          cd build
          cmake --build .

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests with CTest
        run: |
          cd build
          ctest --output-on-failure
